name: Dispatch event of docs files update

on:
  push:
    branches-ignore:
      - 'master'
    paths:
      - 'docs/**'

jobs:
  dispatch_event:
    name: Dispatch event
    runs-on: ubuntu-latest
    steps:
      - id: extract_branch
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - id: dispatch_branch_name
        name: Dispatch branch name with docs update
        run: |
          # curl \
          # -X POST \
          # -H "Accept: application/vnd.github.v3+json" \
          # "https://api.github.com/repos/milvus-io/docs/actions/workflows/updateApiReference.yml/dispatches" \
          # -d '{"ref":"master", "inputs": { "branchName": "${{ steps.extract_branch.outputs.branch }}", "repoName": "${{ github.event.repository.name }}" } }' \
          # -u ".:${{secrets.DOC_TOKEN}}"
          echo '{"ref":"master", "inputs": { "branchName": "${{ steps.extract_branch.outputs.branch }}", "repoName": "${{ github.event.repository.name }}" } }'