name: dispatch local docs files update event

on:
  push:
    paths:
      - 'docs/**'

jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - id: extract_branch
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - id: fetch_tarball_url
        name: Fetch target release URL by tag
        run: |
          # curl \
          # -X POST \
          # -H "Accept: application/vnd.github.v3+json" \
          # "https://api.github.com/repos/milvus-io/docs/actions/workflows/updateApiReference.yml/dispatches" \
          # -d '{"ref":"master", "inputs": { "branchName": "${{ steps.extract_branch.outputs.branch }}", "repoName": "${{ github.event.repository.name }}" } }' \
          # -u ".:${{secrets.DOC_TOKEN}}"
          echo '{"ref":"master", "inputs": { "branchName": "${{ steps.extract_branch.outputs.branch }}", "repoName": "${{ github.event.repository.name }}" } }'