name: Manually triggered workflow

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'tag name test desc'
        required: true

jobs:
  update_branch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.tagName }}!"
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/milvus-io/pymilvus/releases/tags/${{ github.event.inputs.tagName }}" \
            | jq -r '.tarball_url' \
            > ./tarball_url
          export release_url=`cat ./tarball_url`
          echo "$release_url"
          wget "$release_url" -O pymilvus.tar.gz
          sudo mkdir ./pymilvus
          sudo tar -xzvf pymilvus.tar.gz -C pymilvus --strip-components 1
          echo "===untar completed==="
          ls ./pymilvus
          echo "===git clone action-test==="
          sudo git clone https://.:${{ secrets.ACCESS_TOKEN }}@github.com/czhen-zilliz/action-test.git
          git config --global user.email "zhen.chen@zilliz.com"
          git config --global user.name "czhen-zilliz"
          sudo chmod -R 777 action-test
          cd action-test/docs
          if [ -d "./${{ github.event.inputs.tagName }}" ]
          then
            echo "===tag name exists, remove all under this dir==="
            sudo rm -fr "./${{ github.event.inputs.tagName }}"
          else
            echo "===miss tag name, create this dir==="
            sudo mkdir "./${{ github.event.inputs.tagName }}"
          fi
          echo "===copy docs==="
          sudo cp ../../pymilvus/docs/source/* "./${{ github.event.inputs.tagName }}"
          git add .
          git commit -m "Update pymilvus"
          git push -f origin master