name: Manually triggered workflow

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag name'
        required: true
      repoName:
        description: 'Repo name'
        required: true

jobs:
  update_branch:
    runs-on: ubuntu-latest
    steps:
      - id: fetch_tarball_url
        name: Fetch target release URL by tag
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/milvus-io/${{ github.event.inputs.repoName }}/releases/tags/${{ github.event.inputs.tagName }}" \
            | jq -r '.tarball_url' \
            > ./tarball_url
          export release_url=`cat ./tarball_url`
          echo "::set-output name=tarball_url::$release_url"
          echo "=>Completed: Fetching target release URL $release_url."
      - id: download_code
        name: Download and untar release code
        run: |
          wget "${{ steps.vars.outputs.tarball_url }}" -O "${{ github.event.inputs.repoName }}.tar.gz"
          sudo mkdir "./${{ github.event.inputs.repoName }}"
          sudo tar -xzvf "${{ github.event.inputs.repoName }}.tar.gz" -C "${{ github.event.inputs.repoName }}" --strip-components 1
          echo "=>List all doc files"
          ls -l "./${{ github.event.inputs.repoName }}"
          echo "=>Completed: download and untar."
      - id: update_repo
        name: Git clone and update doc repo
        run: |
          sudo git clone https://.:${{ secrets.ACCESS_TOKEN }}@github.com/czhen-zilliz/action-test.git
          git config --global user.email "zhen.chen@zilliz.com"
          git config --global user.name "czhen-zilliz" 
          sudo chmod -R 777 action-test
          cd action-test/pymilvus
          echo "=>List all doc versions"
          ls -l action-test/pymilvus
          if [ -d "./${{ github.event.inputs.tagName }}" ]
          then
            echo "===tag name exists, remove all under this dir==="
            sudo rm -fr "./${{ github.event.inputs.tagName }}"
          else
            echo "===miss tag name, create this dir==="
            sudo mkdir "./${{ github.event.inputs.tagName }}"
          fi
          echo "=>Completed: download and untar."
          sudo cp ../../pymilvus/docs/source/* "./${{ github.event.inputs.tagName }}"
          git add .
          git commit -m "Update pymilvus"
          git push -f origin master