name: Manually triggered workflow

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag name'
        required: true
      repoName:
        description: 'Repo name'
        required: true

jobs:
  update_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Generate docker tag name
        id: generate-tag-name
        run: |
          export tag=${{ github.sha }}-$GITHUB_RUN_NUMBER
          echo $tag
          echo $GITHUB_RUN_NUMBER
          echo "::set-output name=docker_tag::$tag"
      - name: Use docker tag name
        id: use-tag-name
        run: |
          echo ${{ steps.generate-tag-name.outputs.docker_tag }}