name: Manually triggered workflow

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'tag name test desc'
        required: true
        default: 'Mona the Octocat'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
           echo "Hello ${{ github.event.inputs.tagName }}!"
           python --version
           curl \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/milvus-io/pymilvus/releases/tags/${{ github.event.inputs.tagName }}" \
            |  | jq -r '.tarball_url'
