name: Manually triggered workflow

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'tag name test desc'
        required: true
        default: 'Mona the Octocat'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.tagName }}!"
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/milvus-io/pymilvus/releases/tags/${{ github.event.inputs.tagName }}" \
            | jq -r '.tarball_url' \
            > ./tarball_url
          export release_url=`cat ./tarball_url`
          echo "$release_url"
          wget "$release_url" -O pymilvus.tar.gz
          mkdir pymilvus && tar -xzvf pymilvus.tar.gz -C pymilvus --strip-components 1
          cd ./pymilvus
          ls -a

