name: Manually triggered workflow

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'tag name test desc'
        required: true
        default: 'Mona the Octocat'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
           echo "Hello ${{ github.event.inputs.tagName }}!"
           curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/czhen-zilliz/pymilvus/releases/tags/${{ github.event.inputs.tagName }}
