# This is a basic workflow to help you get started with Actions

name: Update the release's assets after it published

# Controls when the workflow will run
on:
  release:
    types: [published]
    branches:
      - cli-win-build

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    container: czhenzilliz/servercore2019_vc

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: "3.8"
      #     architecture: "x64"
      - name: Install requirements
        shell: powershell
        run: >-
          python -m
          pip install
          -e
          .
      - name: Install pyreadline
        shell: powershell
        run: >-
          python -m
          pip install
          pyreadline
      - name: Install pyinstaller
        shell: powershell
        run: >-
          python -m
          pip install
          pyinstaller
      - name: build to dist/
        shell: powershell
        run: |
          pyinstaller -F ./milvus_cli/scripts/milvus_cli.py -p ./milvus_cli --clean --hidden-import pyreadline
      - name: Update assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/*
